### ISSUE TITLE
I have installed kali as a virtual machine whenever i do the command there is like no such file or unable to reach

### ISSUE THREAD

**Issue by rm361** [hacker3983/how-to-install-pyrit-on-kali-linux-2020.1a#2]

**Comment by hacker3983** [comment]
do apt-get upgrade command and try again

**Comment by hacker3983** [comment]
do apt-get upgrade command and try again

**Comment by 3ncrypted1** [comment]
These are just some of the reasons Kali developers no longer include Pyrit in their repos. Pyrit is old, outdated, uses Python2.7 which Kali is already transitioning to Python3x per changelogs, so the Kali repos plus additional code from other programs cause too many exceptions to be worth it. JPMora states its old & outdated in the README file but says he is working on Pyrit for Python3x. https://github.com/JPaulMora/Pyrit       ........Try Hashcat with GPU compile..
