### ISSUE TITLE
Add the repository in the shell script to remove a manual step

### ISSUE THREAD

**Issue by Grezzo** [hacker3983/how-to-install-pyrit-on-kali-linux-2020.1a#5]
Instead of using mousepad to manually edit sources.list, the following command can be added to the shell script at the start:

```
sudo bash -c "echo deb http://ftp.debian.org/debian/ stretch main contrib non-free >> /etc/apt/sources.list"
```

**Comment by hacker3983** [comment]
Yeah i know at the time i made the script i was a beginner learning alot
