### ISSUE TITLE
Some traceback error installing something

### ISSUE THREAD

**Issue by hacker3983** [hacker3983/how-to-install-pyrit-on-kali-linux-2020.1a#7]
Thanks to Guilherme Meyrelles for reporting the issue.
So we get a error like this
```py
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
```
I'm not sure if it because something failed to install will fix this issue soon

**Comment by EmperorTransisthor** [comment]
I've found a solution, will make a pull request tommorow after I test it.

**Comment by hacker3983** [comment]
Oh thank you I have solved the problem already but forgot to close the issue Sent from Mail for Windows 10 From: EmperorTransisthorSent: Monday, May 3, 2021 7:21 PMTo: hacker3983/how-to-install-pyrit-on-kali-linux-2020.1aCc: hacker3983; AuthorSubject: Re: [hacker3983/how-to-install-pyrit-on-kali-linux-2020.1a] Some traceback error installing something (#7) I've found a solution, will make a pull request tommorow after I test it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hacker3983** [comment]
found solution it is the python version.
sorry i forgot to close the issue

**Comment by hacker3983** [comment]
It’s the python version Sent from Mail for Windows 10 From: EmperorTransisthorSent: Monday, May 3, 2021 7:21 PMTo: hacker3983/how-to-install-pyrit-on-kali-linux-2020.1aCc: hacker3983; AuthorSubject: Re: [hacker3983/how-to-install-pyrit-on-kali-linux-2020.1a] Some traceback error installing something (#7) I've found a solution, will make a pull request tommorow after I test it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by EmperorTransisthor** [comment]
Did you already upload solution? Yesterday, when I tried to install pyrit, the error was still here, so you didn't update repo or this solution doesn't work

**Comment by hacker3983** [comment]
Yeah the best way is to check the python version Sent from Mail for Windows 10 From: EmperorTransisthorSent: Tuesday, May 4, 2021 6:39 AMTo: hacker3983/how-to-install-pyrit-on-kali-linux-2020.1aCc: hacker3983; State changeSubject: Re: [hacker3983/how-to-install-pyrit-on-kali-linux-2020.1a] Some traceback error installing something (#7) Did you already upload solution? Yesterday, when I tried to install pyrit, the error was still here, so you didn't update repo or this solution doesn't work—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hacker3983** [comment]
Solution check the python version
